@@grammar::TMI
@@left_recursion :: True

start = decls $;

decls = definition ';' decls | definition;

definition = defpat: {identifier}+ '=' body: exp;

exp = let | binopapp | app | identifier | integer;

let = 'let' '{' decls: decls '}' 'in' body: exp;

binopapp = left: identifier op: operator right: exp;

app = identifier {identifier}+;

identifier = /[a-zA-Z]+/;
_operator = /[+\-_!@$%^&*?]+/;
integer = /[0-9]+/;
operator = /[+]+/;
